spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/online_music?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10240MB
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.fjh.pojo
logging:
  level:
    com.fjh.mapper: DEBUG

## 最大上传单个文件大小：默认1M
#spring.servlet.multipart.max-file-size : 1024MB
#  # 最大上传多个文件大小 ：默认10M
#spring.servlet.multipart.max-request-size: 10240MB

SAVE_PATH: D:\work\
